language: php

php:
  - 7.1

before_install:
  - openssl aes-256-cbc -K $encrypted_278b576efbf2_key -iv $encrypted_278b576efbf2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $STAGING_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- echo "hello world"

deploy:
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/api && git pull' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/api && composer install'
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/api && git pull' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/api && composer install'
    on:
      branch: deploy
